### ISSUE TITLE
Rader i `dommer` med ugyldig kilde_id

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/ub-baser#1]
```
{
    "aar": "1961",
    "id": "1890",
    "kilde_id": "0",
    "navn": "Notfiskdeommen",
    "note": "",
    "side": "554"
}
```

Tipper: kilde_id = 2 (Nordiske domme i sjøfartanliggende), men må sjekkes.

```
{
    "aar": "1971",
    "id": "1821",
    "kilde_id": "144",
    "navn": "Pierson-vinduet",
    "note": "",
    "side": "144"
}
```

Må sjekkes.

**Comment by ewinge** [comment]
Notfiskdommen Rt. 1961 s. 554. 
https://www.google.com/search?client=firefox-b-d&q=Notfiskdommen

**Comment by ewinge** [comment]
Pierson-vinduet Rt. 1971 s. 144
http://folk.uio.no/olavt/Dommer/hr/Rt-1971-144.htm

**Comment by danmichaelo** [comment]
https://ub-baser.uio.no/dommer/3781

https://ub-baser.uio.no/dommer/3717
