### ISSUE TITLE
Dommer teller feil

### ISSUE THREAD

**Issue by ewinge** [scriptotek/ub-baser#25]
Viser 0 til 0 av 0 poster

**Comment by danmichaelo** [comment]
Ah, kommer herfra: https://github.com/scriptotek/ub-baser/blob/c5a30b0ef9c380d95aeecdee31f220915d448c87/app/Http/Controllers/RecordController.php#L175-L181

Dommer er den eneste som bruker views, de andre basene bruker enten vanlige tabeller eller materialized view. Sikkert greit å bytte til materialized view for dommer også, så blir det mindre forskjellige ting å forholde seg til.
